version: '3.2'

services:

  nginx:
    image: nginx:1-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./web:/www/public_html/web
      - ./wordpress:/www/public_html/wordpress
      - ./config/nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - web

  php:
    build: ./docker/php
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_local
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: hoals.orkdasd.ioutrna.otuwymvlp.ieuqhqbm
      WORDPRESS_DEBUG: 1
    volumes:
      - ./web:/www/public_html/web
      - ./wp-config.php:/www/public_html/wp-config.php
      - ./wordpress:/www/public_html/wordpress
    depends_on:
      - db
    networks:
      - web

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_local
      MYSQL_ROOT_PASSWORD: hoals.orkdasd.ioutrna.otuwymvlp.ieuqhqbm
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - web

volumes:
  db_data: {}

networks:
  web: {}
